projeto-spring:
  viacep-url: https://viacep.com.br/ws
  swagger:
    title: Projeto DIO de Padrões de Projeto (Patterns) API
    description: Documentação on-line da API
    contact:
      name: Alberto Yano
      email: alberto.yano@gmail.com
      url: https://www.linkedin.com/in/albertoyano/
spring:
  application:
    name: projeto-spring
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS DIO_LAB;
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      schema: DIO_LAB
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
  h2:
    console:
      enabled: true